# Generated by Django 5.2.9 on 2025-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Picked Up', 'Picked Up'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
